# Generated by Django 4.2.20 on 2025-04-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='files.file')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='files_file_name_350fdc_idx'), models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'), models.Index(fields=['size'], name='files_file_size_6009e9_idx'), models.Index(fields=['upload_date'], name='files_file_upload__10ed84_idx')],
            },
        ),
    ]
