# Generated by Django 4.2.20 on 2025-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_name_350fdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_file_ty_2d7e73_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_size_6009e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_upload__10ed84_idx',
        ),
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
